### ISSUE TITLE
Add "payload" to ReplyButton

### ISSUE THREAD

**Issue by sunqiang25** [just-ai/aimybox-android-sdk#50]
if (json.has("buttons"))
                replies.add(ButtonsReply(
                    json["buttons"].asJsonArray.map { it.asJsonObject }.map { btn ->
                        ReplyButton(btn["title"].asString, null)
                    }
                ))

templates:
  utter_greet:
  - text: "Hey! How are you?"
    buttons:
    - title: "great"
      payload: "great"
    - title: "super sad"
      payload: "super sad"

**Comment by morfeusys** [comment]
@sunqiang25 if you plan to send button's payload back to the Rasa server, you have to override a `ReplyButton` and `Button` classes and then - implement an onButtonClick inside the custom `AimyboxAssistantViewModel`. Because a button's payload - is a specific Rasa's feature and it cannot be general for every assistant based on the SDK.

**Comment by sunqiang25** [comment]
@morfeusys Thanks morfeusys, I have another question, error messgae "E/SpeechRecognizer: bind to recognition service failed" in AS console when I use HUAWEI device, MI device is ok , Why is it so different? Thanks in advance!

**Comment by morfeusys** [comment]
@sunqiang25 it maybe lack of built-in speech recognition system from Google on Huawei devices. That is why it's not possible for assistant to recognise speech. You may replace it with some other speech-to-text module. Please read more on https://help.aimybox.com/en/article/speech-to-text-components-1o8c1e5/

**Comment by sunqiang25** [comment]
@morfeusys Hi morfeusys, It's true that I can override the class, but I think button's payload is a common feature, we can set the same value in title as in payload, I can also set it to a different value, I think it's more flexible, do you think?

**Comment by morfeusys** [comment]
@sunqiang25 maybe it's a good idea to add a payload field into `ReplyButton` class as an optional attribute, meaning that it's `title` field would be passed to the query.

**Comment by morfeusys** [comment]
@sunqiang25 implemented in 0.8.0 and components 0.1.8
