### ISSUE TITLE
How to get the intent in Rasa server Response

### ISSUE THREAD

**Issue by julenmerchan** [just-ai/aimybox-android-sdk#83]
Hi, I've followed this [tutorial](https://blog.rasa.com/how-to-build-a-mobile-voice-assistant-with-open-source-rasa-and-aimybox/)  for building a voice assistant in my Android app, now I'm handling the responses I get from my Rasa server and I've realized that always, these reponses arrive to my app with action and intent = null, here is an example: 

 RasaResponse(query=hola, action=null, intent=null, question=true, replies=[com.justai.aimybox.model.reply.TextReply@5cbfc22])

Does anyone know how to configure Rasa or Aimybox to get the intent in the response? I've tried a lot of things that I've found searching but anything works.

**Comment by morfeusys** [comment]
It's impossible to retrieve an intent name from the Rasa's response, because Aimybox uses its REST API that performs action on the Rasa side. You can use [JAICF](https://github.com/just-ai/aimybox-android-sdk/tree/master/jaicf-api) together with [Rasa](https://github.com/just-ai/jaicf-kotlin/tree/master/activators/rasa) to create a dialogue scenario - in this case your scenario will retrieve an intent name and perform some action on the Android side.

**Comment by julenmerchan** [comment]
Many thanks for your reply, I'm going to investigate about it. :)

**Comment by julenmerchan** [comment]
Hi, I'm trying to connect JAICF with Rasa following the tutorials you've sent me but every time I send a POST request to the Rasa server with my app, I get 404 NOT ALLOWED  code in ngrok, here is my AimyboxApplication class: 

class AimyboxApplication : Application(), AimyboxProvider {

    companion object {
        private const val AIMYBOX_API_KEY = "Ldf0j7WZi3KwNah2aNeXVIACz0lb9qMH"
        var myAimybox: Aimybox? = null
    }

    override val aimybox by lazy {
        createAimybox(this)
    }


    fun createAimybox(context: Context): Aimybox {

        val assetsKaldi = KaldiAssets.fromApkAssets(context, "vosk-model-small-es-0.3")

        val unitId = UUID.randomUUID().toString()
        val voiceTrigger = KaldiVoiceTrigger(assetsKaldi, listOf(context.getString(R.string.wakeWord1), context.getString(R.string.wakeWord2), context.getString(R.string.wakeWord3)))

        var textToSpeech =   GooglePlatformTextToSpeech(context, Locale.getDefault())

        var speechToText = GooglePlatformSpeechToText(context, Locale.getDefault())

        val RasaBot = BotEngine(
                MainScenario.model,
                activators = arrayOf(
                        RasaIntentActivator.Factory(RasaApi("https://4c498b3b9cac.ngrok.io/webhooks/rest/webhook"))
                )
        )

        val dialogApi = JAICFDialogApi(unitId, RasaBot)

//        val dialogApi = RasaDialogApi(unitId, "https://4c498b3b9cac.ngrok.io/webhooks/rest/webhook")

        return Aimybox(Config.create(speechToText, textToSpeech, dialogApi) {
            this.voiceTrigger = voiceTrigger
        })
    }
}

**Comment by morfeusys** [comment]
Please say me your rada version

**Comment by morfeusys** [comment]
Looks like the problem in your url. You don't have to define webhook. You need a Rasa NLU HTTP API url instead.

**Comment by julenmerchan** [comment]
Thanks for your replies my Rasa version:

Rasa Version     : 2.0.2
Rasa SDK Version : 2.0.0
Rasa X Version   : None
Python Version   : 3.8.3
Operating System : Windows-10-10.0.18362-SP0

I've changed the url to: https://4c498b3b9cac.ngrok.io but still having the same problem.

**Comment by morfeusys** [comment]
@julenmerchan please show me your `MainScenario` to learn how you react on any intent from Rasa.
Today we're planning to publish new version of rasa library that works with 2.x Rasa version. Now it works with only 1.9.x

**Comment by julenmerchan** [comment]
Hi @morfeusys, I've picked an example just to see how it works, anyway here is my MainScenario:

package assistant.models

import com.justai.jaicf.activator.rasa.rasa
import com.justai.jaicf.model.scenario.Scenario

object MainScenario: Scenario() {
    init {
        state("launch") {
            activators {
                intent("greet")
            }

            action {
                // Recognised named entities
                val slots = activator.rasa?.slots
            }
        }
    }
}

**Comment by morfeusys** [comment]
Well, how I can see there is no any response you generate with some `reactions.say()` for example in your `action` block. Thus Aimybox of course doesn't speak in response to your request..

**Comment by julenmerchan** [comment]
Hi, I've made the change in my MainScenario and now Aimybox can speak, however debugging my project I see the respose has null intent and text and void replies:

AimyboxBotResponse(query=hola, text=null, action=null, intent=null, question=true, data={}, replies=[])

My MainScenario file now: 

package assistant.models

import com.justai.jaicf.activator.rasa.rasa
import com.justai.jaicf.channel.aimybox.aimybox
import com.justai.jaicf.model.scenario.Scenario

object MainScenario: Scenario() {
    init {
        state("launch") {
            activators {
                catchAll()
                intent("greet")
            }

            action {
                reactions.run {
                    say("hola hola!")
                    aimybox?.endConversation()
                }
            }
        }
    }
}

**Comment by morfeusys** [comment]
@julenmerchan please take a look on this sample app that uses Rasa with jaicf https://github.com/just-ai/jaicf-android-template

**Comment by julenmerchan** [comment]
Hi @morfeusys, many thanks for your answer after upgrading the version of jaicf rasa and jaicf aimybox to 0.8.2 all works perfectly
