### ISSUE TITLE
Передавать параметр - x-data-logging-enabled в Yandex.Speechkit

### ISSUE THREAD

**Issue by Ozyrus** [just-ai/aimybox-android-sdk#85]
При запросе к Yandex SpeechKit  Яндекс.Облака для диагностики ошибок необходимо передавать разрешение сохранять данные, переданные пользователем в запросе. В соответствии с документацией Яндекса https://cloud.yandex.ru/docs/speechkit/concepts/support-headers данное разрешение передается в параметре - x-data-logging-enabled.

На текущий момент при использовании SDK AimyBox для Android нет возможности передать данный параметр в запросе к Yandex SpeechKit.

Необходимо в объекты com.justai.aimybox.speechkit.yandex.cloud.YandexTextToSpeech и com.justai.aimybox.speechkit.yandex.cloud.YandexSpeechToText  добавить возможность передачи параметра x-data-logging-enabled.

**Comment by bgubanov** [comment]
#88
