### ISSUE TITLE
Добавить событие для отслеживания метрик Yandex SpeechKit

### ISSUE THREAD

**Issue by GSAleksandrov** [just-ai/aimybox-android-sdk#87]
Для отслеживания метрик работы голосового помощника необходимо получать информацию о времени обработки запроса TextToSpeech в Yandex SpeechKit Яндекс.Облака. На текущий момент при использовании SDK AimyBox для Android нет возможности отслеживать данную метрику, есть возможность только получить время запроса с учетом времени, которое еще требуется на произнесение текста.
Необходимо добавить возможность передачи времени ответа или факт получения успешного ответа от Yandex SpeechKit

**Comment by bgubanov** [comment]
Факт получения успешного ответа можно отследить в aimybox.textToSpeechEvents, событие Event.SpeechDataReceived
Перед запросом в textToSpeechEvents посылается событие Event.SpeechStarted, при успешном получении и перед проигрыванием аудио посылается событие Event.SpeechDataReceived
При отмене отправляется событие Event.SpeechSkipped, при ошибке во время запроса в aimybox.exceptions отправляется TextToSpeechException (где поле cause является YandexCloudTextToSpeechException)
Таким образом, отслеживание времени ответа Яндекс.Облака возможно
Если я вас неправильно понял, прошу уточнить

**Comment by GSAleksandrov** [comment]
Поняли правильно, сейчас проверяем заработает ли, по результатам проверки отпишусь
