### ISSUE TITLE
Kaldi Speechkit Dependency

### ISSUE THREAD

**Issue by taschwer** [just-ai/aimybox-android-sdk#99]
I cannot build a project using aimybox because I get the following gradle build error:
"Could not GET 'https://dl.bintray.com/alphacep/vosk/com/alphacep/vosk-android/0.3.17/vosk-android-0.3.17.pom'. Received status code 403 from server: Forbidden
Disable Gradle 'offline mode' and sync project"
Gradle offline mode is already disabled so that cannot be the problem. You use the the dependency mentioned above in the Kaldi Speechkit of your SDK. Please update the Vosk dependency to a newer version. Vosk has newer versions of the library hosted on https://alphacephei.com/maven.

**Comment by bgubanov** [comment]
Hello. We are aware of the problem, a new version of sdk will be released soon.

**Comment by taschwer** [comment]
Thanks

**Comment by bgubanov** [comment]
Hello. A new 0.16.5 version is available from mavenCentral. You can get it with
`implementation("com.just-ai.aimybox:kaldi-speechkit:0.16.5")`

**Comment by taschwer** [comment]
Thank you
